name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 push될 때 실행

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # v3 → v4

    - name: Setup Node.js
      uses: actions/setup-node@v4  # v3 → v4
      with:
        node-version: 22.11.0 # Node.js 버전

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Upload artifact for deployment
      uses: actions/upload-pages-artifact@v3  # v1 → v3
      with:
        path: ./dist # 빌드 결과물이 위치한 디렉토리

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4  # v2 → v4
